language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true

# command to prepare the system to install prerequisites or dependencies
before_install:
 - pip install -U pip
 - sudo add-apt-repository -y ppa:donk/gstreamer
 - sudo apt-get -qq update
 - sudo apt-get install python-setuptools
 - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-networkx
 - sudo apt-get install -qq libhdf5-serial-dev python-h5py python-tables
 - sudo apt-get install -qq python-gst0.10 gstreamer0.10-plugins-good gstreamer0.10-gnonlin gstreamer0.10-plugins-ugly gstreamer0.10-plugins-bad

# command to install dependencies
install: 
# - "pip install -r requirements.txt --use-mirrors"
- python setup.py install


# command to run tests
before_script:
- pip install -U coverage
- pip install coveralls

script:
 - coverage run --source=timeside --omit=timeside/analyzer/aubio/aubio_*.py,timeside/analyzer/yaafe.py,timeside/analyzer/limsi_sad.py,timeside/analyzer/vamp_plugin.py setup.py test

after_success:
 - coveralls