sudo: required

language: python

services:
  - docker

install:
  - docker-compose --version
  - docker-compose build app src
  - docker-compose run src  # build C library


script:
  - docker-compose run app python -c"import timeside.core; timeside.core.list_processors()"
  - docker-compose run app sh -c "cd /srv/src/timeside-diadems; pip install -U coverage; coverage run --source=timeside.plugins.diadems setup.py test"
