language: python
python:
  - "2.6"
  - "2.7"
  
# command to prepare the system to install prerequisites or dependencies
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -qq libhdf5-serial-dev
 - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran

# command to install dependencies
install: 
 - "pip install -r requirements.txt --use-mirrors"

# command to run tests
script:
 - "python setup.py install"
# - "python tests/testcomponent.py"
