language: python
python:
  - "2.7"

#virtualenv:
# system_site_packages: true

# command to prepare the system to install prerequisites or dependencies
before_install:
  - sudo add-apt-repository -y ppa:donk/gstreamer
  - sudo apt-get -qq update
  - export DEBIAN_PACKAGES=$(egrep -v "^\s*(#|$)" debian-requirements.txt)
  - sudo apt-get install -qq $DEBIAN_PACKAGES 

# Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
# Useful for debugging any issues with conda
  - conda info -a
# Install binary dependencies with conda
  - echo $TRAVIS_PYTHON_VERSION
  - conda create -q -n test-environment -c piem --file conda-requirements.txt python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

# Install TimeSide
install:
 - pip install -r requirements.txt


# command to run tests
before_script:
 - pip install -U coverage
 - pip install python-coveralls

script:
 - python -c"import timeside.core; timeside.core.processor.list_processors()"
 - coverage run --source=timeside.plugins.diadems setup.py test

after_success:
 - coveralls